{% raw %}
set dotenv-required := true

[private]
open URL:
    xdg-open {{URL}}

view NAVIGATION=`echo -e "pipelines\nissues\nmerge_requests\ntags\ncommits\nbranches\nreleases" | fzf`:
    echo {{NAVIGATION}}
    just open "$PROJECT_URL/-/{{NAVIGATION}}"
    
repo: (open "$PROJECT_URL")

container_registry: (open "$PROJECT_URL/container_registry")
{% endraw %}